build:
  before_script:
    - "nix-env -iA cachix -f https://cachix.org/api/v1/install"
    - "cachix use thalesmg"
  image: nixos/nix:latest
  script:
    - "nix-build release.nix | cachix push thalesmg"
    - "mkdir -p ./dist/"
    - "cp -r ./result/* ./dist/"
  stage: build
deploy:branch:
  before_script:
    - "apk add --no-cache ruby-dev npm"
    - "(cd fns && npm i)"
    - "gem install dpl"
  image: alpine:latest
  script:
    - "dpl --provider netlify --site 06890b1e-d940-4c61-b50c-59c6b3344838 --auth \"${NETLIFY_TOKEN}\" --dir ./dist/ --functions ./fns/ --no-prod"
  stage: deploy
deploy:prod:
  before_script:
    - "apk add --no-cache ruby-dev npm"
    - "(cd fns && npm i)"
    - "gem install dpl"
  image: alpine:latest
  only:
    refs:
      - master
  script:
    - "dpl --provider netlify --site 06890b1e-d940-4c61-b50c-59c6b3344838 --auth \"${NETLIFY_TOKEN}\" --dir ./dist/ --functions ./fns/ --prod"
  stage: deploy
stages:
  - build
  - deploy
