name:                bumba
version:             0.0.0.0
github:              "thalesmg/bumba"
license:             GPL-3
author:              "Thales Macedo Garitezi"
maintainer:          "thalesmg@gmail.com"
copyright:           "GPLv3"

extra-source-files:
  - Readme.org
  - CHANGELOG.md

synopsis:            "A Reflex(-DOM) skeleton project"
category:            Utils

description:         Please see the README on GitHub at <https://github.com/thalesmg/bumba#Readme.org>

dependencies:
  - base >= 4.7 && < 5
  - reflex
  - reflex-dom
  - text
  - jsaddle
  - jsaddle-dom
  - ghcjs-dom
  - time
  - aeson
  - regex-tdfa

executables:
  bumba:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    when:
      - condition: impl(ghcjs)
        ghc-options:
          - -dedupe
